# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      # choose the right version, which include the maven, otherwise the mvn deploy will fail
      - image: cimg/android:2023.02
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies


      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # Build
      - run:
          name: build
          command: ./gradlew clean assemble

      - run:
          name: Setup emulator
          command: sdkmanager "system-images;android-16;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-16;default;armeabi-v7a"
      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel auto -verbose
          background: true
      - run:
          name: Wait emulator
          command: |
            # wait for it to have booted
            circle-android wait-for-boot
            # unlock the emulator screen
            sleep 30
            adb shell input keyevent 82
      - run:
          name: Run EspressoTests
          command: ./gradlew connectedDemoDebugAndroidTest

      # run tests
      - run:
          name: run tests
          command: ./gradlew test

      - store_test_results:
          path: app/build/test-results
            #- run:
          #  name: Authenticate with GitHub Packages
          # command: |
          #  echo $GITHUB_TOKEN
          # echo $GITHUB_USERNAME

          #run mvn
          # - run:
          #  name: run mvn
          #  command: |
          #  mvn clean deploy

      # Invoke jobs via workflows
      # See: https://circleci.com/docs/2.0/configuration-reference/#workflows
